---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.large
      ami: ami-0189d76e  # Ubuntu 16.04 LTS
      keypair: ajeet # pem file name
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: elk  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         volumes:
          - device_name: /dev/sda1
            volume_size: 20
         count_tag:
            Name: Demo_Master
         instance_tags:
            Name: Demo_master
         vpc_subnet_id: subnet-6df29b04
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: elk
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"


- hosts: elk
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
   - { role: java }
   - { role: elasticsearch }
   - { role: kibana }
   - { role: nginx }
   - { role: logstash }
